# 02 Experiments (protocol v2): re-running the method described in the dissertation

Runs in Google Colab (GPU recommended). Implements dissertation Chapter 4 as the specification, with a clean protocol:

1. **Training pool** = DAIC-WOZ train + dev (140). **Held-out**: DAIC-WOZ official test (46) and E-DAIC (112), each scored once.
2. Architecture and graph hyperparameters fixed at the values the dissertation reports (Table 9). Optuna (TPE) tunes
   learning rate, weight decay, epochs and the class-weight multiplier m, by repeated stratified 5-fold CV inside the pool.
3. **Cross-fitted ensemble**: 5 folds x 4 seeds = 20 members. The threshold is calibrated on the out-of-fold probabilities
   of these same members (fewest false negatives with false-positive rate <= 6/21).

v1 (results in `results/experiments/`) tuned 9 hyperparameters on 107 participants and calibrated the threshold on
different models than the ones that scored the cohorts; its operating points were unstable. v2 results go to
`results/experiments/v2/`.

Deliberate changes from the legacy code: paralinguistic tags counted correctly, no 0.5 s turn filter, tags removed from the
lexical view, psycholinguistic view from `data/mapping/phq8_dsm5_empath.json`.
Only aggregates are written to the repository. Per-participant outputs go to `OUTPUT_DIR`, outside it.

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
import os, sys
REPO = '/content/drive/MyDrive/05_Mestrado/Repositórios/depression-gnn-local/depression-gnn'
os.environ['DAIC_DATA_DIR'] = '/content/drive/MyDrive/Colab Notebooks/datasets'
OUTPUT_DIR = '/content/drive/MyDrive/Colab Notebooks/outputs/paper1/v2'   # outside the repository
os.makedirs(OUTPUT_DIR, exist_ok=True)
os.chdir(REPO)
sys.path.insert(0, REPO)

In [ ]:
!pip install -q -r requirements.txt
!python -m pytest -q tests

.......................                                                  [100%]
=============================== warnings summary ===============================
tests/test_experiment.py::test_run_final[inductgcn-words-views0]
  /content/drive/MyDrive/05_Mestrado/Repositórios/depression-gnn-local/depression-gnn/src/paper1_graph_model/models.py:53: UserWarning: Sparse invariant checks are implicitly disabled. Memory errors (e.g. SEGFAULT) will occur when operating on a sparse tensor which violates the invariants, but checks incur performance overhead. To silence this warning, explicitly opt in or out. See `torch.sparse.check_sparse_tensor_invariants.__doc__` for guidance.  (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:760.)
    a = torch.sparse_coo_tensor(edge_index, edge_weight, (x.shape[0], x.shape[0]))

tests/test_experiment.py::test_run_final[gcn_gat-words-views2]
tests/test_experiment.py::test_run_final[gcn_gat-words-views2]
tests/test_experiment.py::test_run_final[gat-empath-views4]
tests/test_experiment.py::test_run_final[gat-empath-views4]
  /content/drive/MyDrive/05_Mestrado/Repositórios/depression-gnn-local/depression-gnn/src/paper1_graph_model/experiment.py:156: RuntimeWarning: Mean of empty slice
    self.mean = np.nanmean(x, axis=0) if self.cols else np.zeros(0)

tests/test_experiment.py::test_run_final[gcn_gat-words-views2]
tests/test_experiment.py::test_run_final[gcn_gat-words-views2]
tests/test_experiment.py::test_run_final[gat-empath-views4]
tests/test_experiment.py::test_run_final[gat-empath-views4]
  /usr/local/lib/python3.13/dist-packages/numpy/lib/_nanfunctions_impl.py:2053: RuntimeWarning: Degrees of freedom <= 0 for slice.
    var = nanvar(a, axis=axis, dtype=dtype, out=out, ddof=ddof,

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
23 passed, 9 warnings in 39.73s

## Configuration

In [ ]:
import torch
N_TRIALS = 30          # Optuna trials per model (restricted space: 4 hyperparameters)
N_FOLDS = 5
N_REPEATS = 2          # repeated CV inside the objective
SEEDS_PER_FOLD = 4     # ensemble = N_FOLDS * SEEDS_PER_FOLD = 20 members
SEED = 42
MAX_FPR = 6 / 21
SPACE = 'restricted'   # or 'full' for all of dissertation Table 9
STUDY_VERSION = 'v2'
DEVICE = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
STORAGE = f'sqlite:///{OUTPUT_DIR}/optuna.db'   # resumable if the runtime disconnects
print(DEVICE, torch.__version__)

cuda 2.11.0+cu130

## Cohorts and features

In [ ]:
from src.common import data
from src.common.features import EmpathScorer
from src.paper1_graph_model.corpus import build_cohorts
from src.paper1_graph_model.experiment import merge_cohorts

scorer = EmpathScorer()
cohorts = build_cohorts(data.data_root(), scorer, psycholinguistic='dsm5')
pool = merge_cohorts('daic_pool', cohorts['daic_train'], cohorts['daic_dev'])
held_out = [cohorts['daic_test'], cohorts['edaic']]
for c in [pool] + held_out:
    print(f'{c.name:12s} n={len(c.y):4d} positives={int(c.y.sum()):3d}')

daic_pool    n= 140 positives= 42
daic_test    n=  46 positives= 14
edaic        n= 112 positives= 34

## Models (rows of dissertation Table 11)

In [ ]:
from src.paper1_graph_model.experiment import ModelSpec
ALL = ('temporal', 'paralinguistic', 'psycholinguistic')
CATS = scorer.categories
SPECS = [
    ModelSpec('InductGCN',                      'inductgcn', 'words',  ()),
    ModelSpec('GAT text-only',                  'gat',       'words',  ()),
    ModelSpec('GCN+GAT hybrid',                 'gcn_gat',   'words',  ALL),
    ModelSpec('EmpathGCN',                      'gcn',       'empath', ('psycholinguistic',), CATS),
    ModelSpec('GAT-GCN-FeExtr (Empath graph)',  'gat',       'empath', ALL, CATS),
    ModelSpec('GAT-GCN-FeExtr (word graph)',    'gat',       'words',  ALL),
]

## Hyperparameter search (training pool only)

In [ ]:
import json, pathlib
from src.paper1_graph_model.experiment import tune, hp_from_params
RESULTS = pathlib.Path('results/experiments/v2'); RESULTS.mkdir(parents=True, exist_ok=True)

best = {}
for spec in SPECS:
    study = tune(spec, pool, N_TRIALS, N_FOLDS, N_REPEATS, SEED, DEVICE, storage=STORAGE,
                 space=SPACE, study_name=f'{spec.name} [{STUDY_VERSION}]')
    best[spec.name] = {'params': study.best_params, 'cv_pr_auc': study.best_value,
                       'n_trials': len(study.trials), 'space': SPACE}
    print(f'{spec.name:32s} CV PR-AUC={study.best_value:.3f}  {study.best_params}')
(RESULTS / 'best_params.json').write_text(json.dumps(best, indent=2))

[I 2026-10-19 01:42:53,150] A new study created in RDB with name: InductGCN [v2]
/content/drive/MyDrive/05_Mestrado/Repositórios/depression-gnn-local/depression-gnn/src/paper1_graph_model/models.py:53: UserWarning: Sparse invariant checks are implicitly disabled. Memory errors (e.g. SEGFAULT) will occur when operating on a sparse tensor which violates the invariants, but checks incur performance overhead. To silence this warning, explicitly opt in or out. See `torch.sparse.check_sparse_tensor_invariants.__doc__` for guidance.  (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:760.)
  a = torch.sparse_coo_tensor(edge_index, edge_weight, (x.shape[0], x.shape[0]))
[I 2026-10-19 01:43:12,687] Trial 0 finished with value: 0.47483264567672756 and parameters: {'lr': 0.0005611516415334506, 'weight_decay': 0.0039847274093219665, 'epochs': 550, 'm': 3.79597545259111}. Best is trial 0 with value: 0.47483264567672756.
[I 2026-10-19 01:43:20,756] Trial 1 finished with value: 0.44982495272469086 and parameters: {'lr': 0.0002051338263087451, 'weight_decay': 0.00010255552094216992, 'epochs': 300, 'm': 4.598528437324806}. Best is trial 0 with value: 0.47483264567672756.
[I 2026-10-19 01:43:28,899] Trial 2 finished with value: 0.4670662216887262 and parameters: {'lr': 0.0015930522616241021, 'weight_decay': 0.0013035123791853842, 'epochs': 300, 'm': 4.909729556485983}. Best is trial 0 with value: 0.47483264567672756.
[I 2026-10-19 01:43:38,338] Trial 3 finished with value: 0.43220891417414775 and parameters: {'lr': 0.004622589001020831, 'weight_decay': 0.0001329377199163636, 'epochs': 350, 'm': 2.5502135295603017}. Best is trial 0 with value: 0.47483264567672756.
[I 2026-10-19 01:43:50,402] Trial 4 finished with value: 0.5189751790495908 and parameters: {'lr': 0.0004059611610484307, 'weight_decay': 0.0005603803105930283, 'epochs': 450, 'm': 2.8736874205941256}. Best is trial 4 with value: 0.5189751790495908.
[I 2026-10-19 01:44:01,167] Trial 5 finished with value: 0.460660570975725 and parameters: {'lr': 0.0016738085788752138, 'weight_decay': 9.505122659935192e-05, 'epochs': 400, 'm': 3.099085529881075}. Best is trial 4 with value: 0.5189751790495908.
[I 2026-10-19 01:44:10,780] Trial 6 finished with value: 0.49300999315484273 and parameters: {'lr': 0.000816845589476017, 'weight_decay': 0.0018591820902866042, 'epochs': 350, 'm': 3.5427033152408347}. Best is trial 4 with value: 0.5189751790495908.
[I 2026-10-19 01:44:24,046] Trial 7 finished with value: 0.4521999361731976 and parameters: {'lr': 0.0015304852121831463, 'weight_decay': 6.192568649430468e-05, 'epochs': 500, 'm': 2.5115723710618747}. Best is trial 4 with value: 0.5189751790495908.
[I 2026-10-19 01:44:40,166] Trial 8 finished with value: 0.46050067570326086 and parameters: {'lr': 0.00013492834268013249, 'weight_decay': 0.003951309774854116, 'epochs': 600, 'm': 4.425192044349384}. Best is trial 4 with value: 0.5189751790495908.
[I 2026-10-19 01:44:53,463] Trial 9 finished with value: 0.5122670689977746 and parameters: {'lr': 0.0004066563313514797, 'weight_decay': 7.839966958361505e-05, 'epochs': 500, 'm': 3.3204574812188037}. Best is trial 4 with value: 0.5189751790495908.
[I 2026-10-19 01:45:01,771] Trial 10 finished with value: 0.488613432323499 and parameters: {'lr': 0.00018463386234836822, 'weight_decay': 0.0008901412971904829, 'epochs': 300, 'm': 2.337548629458454}. Best is trial 4 with value: 0.5189751790495908.
[I 2026-10-19 01:45:13,976] Trial 11 finished with value: 0.47135175694531906 and parameters: {'lr': 0.00015051854433171602, 'weight_decay': 0.00035681774922032293, 'epochs': 450, 'm': 3.7453904926718558}. Best is trial 4 with value: 0.5189751790495908.
[I 2026-10-19 01:45:27,643] Trial 12 finished with value: 0.4957230695372689 and parameters: {'lr': 0.0005283864474907013, 'weight_decay': 0.0005353171264348171, 'epochs': 500, 'm': 3.078225459720201}. Best is trial 4 with value: 0.5189751790495908.
[I 2026-10-19 01:45:42,597] Trial 13 finished with value: 0.44907815641380766 and parameters: {'lr': 0.0019520650066128266, 'weight_decay': 5.1670770584972945e-05, 'epochs': 550, 'm': 3.560223525363324}. Best is trial 4 with value: 0.5189751790495908.
[I 2026-10-19 01:45:54,839] Trial 14 finished with value: 0.5071598153442948 and parameters: {'lr': 0.0005008920981730146, 'weight_decay': 0.00015360149209993026, 'epochs': 450, 'm': 3.744454067264888}. Best is trial 4 with value: 0.5189751790495908.
[I 2026-10-19 01:46:07,147] Trial 15 finished with value: 0.47891215014200456 and parameters: {'lr': 0.0001469861255217707, 'weight_decay': 0.00012810339243780625, 'epochs': 450, 'm': 2.8387145810478716}. Best is trial 4 with value: 0.5189751790495908.
[I 2026-10-19 01:46:23,184] Trial 16 finished with value: 0.4933453099668657 and parameters: {'lr': 0.0002486288335152394, 'weight_decay': 9.471215614066115e-05, 'epochs': 600, 'm': 4.401146185630592}. Best is trial 4 with value: 0.5189751790495908.
[I 2026-10-19 01:46:36,688] Trial 17 finished with value: 0.4959705795221217 and parameters: {'lr': 0.00021895605531409843, 'weight_decay': 0.002421014128608311, 'epochs': 500, 'm': 2.863118985428147}. Best is trial 4 with value: 0.5189751790495908.
[I 2026-10-19 01:46:50,152] Trial 18 finished with value: 0.5026512531802083 and parameters: {'lr': 0.00022765563906525251, 'weight_decay': 0.0004907308738900384, 'epochs': 500, 'm': 2.2136412750245724}. Best is trial 4 with value: 0.5189751790495908.
[I 2026-10-19 01:46:59,560] Trial 19 finished with value: 0.47564421004553037 and parameters: {'lr': 0.0002539415003366435, 'weight_decay': 0.00010013728686758849, 'epochs': 350, 'm': 3.30551353361417}. Best is trial 4 with value: 0.5189751790495908.
[I 2026-10-19 01:47:11,836] Trial 20 finished with value: 0.4809995667391982 and parameters: {'lr': 0.0005904870869755008, 'weight_decay': 0.0007122400277839258, 'epochs': 450, 'm': 2.0751629888955687}. Best is trial 4 with value: 0.5189751790495908.
[I 2026-10-19 01:47:23,963] Trial 21 finished with value: 0.48694850380307975 and parameters: {'lr': 0.00029905397748612413, 'weight_decay': 0.0002184329182830317, 'epochs': 450, 'm': 4.2311567321598975}. Best is trial 4 with value: 0.5189751790495908.
[I 2026-10-19 01:47:36,293] Trial 22 finished with value: 0.5023876429622961 and parameters: {'lr': 0.000521223562289381, 'weight_decay': 0.00022613731744061647, 'epochs': 450, 'm': 2.6606923004671503}. Best is trial 4 with value: 0.5189751790495908.
[I 2026-10-19 01:47:49,712] Trial 23 finished with value: 0.5151572936017073 and parameters: {'lr': 0.00039314012732359876, 'weight_decay': 9.659556536154613e-05, 'epochs': 500, 'm': 3.118312563656724}. Best is trial 4 with value: 0.5189751790495908.
[I 2026-10-19 01:48:06,019] Trial 24 finished with value: 0.5055649180219618 and parameters: {'lr': 0.00022294217981538533, 'weight_decay': 5.183953719617539e-05, 'epochs': 600, 'm': 2.8650532689050747}. Best is trial 4 with value: 0.5189751790495908.
[I 2026-10-19 01:48:20,808] Trial 25 finished with value: 0.46275106725931503 and parameters: {'lr': 0.0011476124682695326, 'weight_decay': 0.00012495117168176686, 'epochs': 550, 'm': 3.463970467500175}. Best is trial 4 with value: 0.5189751790495908.
[I 2026-10-19 01:48:35,489] Trial 26 finished with value: 0.508631154468596 and parameters: {'lr': 0.00029678577603869195, 'weight_decay': 0.00013413895011712737, 'epochs': 550, 'm': 3.3045224953411516}. Best is trial 4 with value: 0.5189751790495908.
[I 2026-10-19 01:48:46,251] Trial 27 finished with value: 0.4904241047067052 and parameters: {'lr': 0.0002925407785820309, 'weight_decay': 0.00023177982456766007, 'epochs': 400, 'm': 3.2212550358053105}. Best is trial 4 with value: 0.5189751790495908.
[I 2026-10-19 01:48:59,864] Trial 28 finished with value: 0.5105990431100422 and parameters: {'lr': 0.0002693512550505391, 'weight_decay': 0.0001444827284133387, 'epochs': 500, 'm': 2.3215802525467737}. Best is trial 4 with value: 0.5189751790495908.
[I 2026-10-19 01:49:14,341] Trial 29 finished with value: 0.5122026032116007 and parameters: {'lr': 0.00034012298961144866, 'weight_decay': 0.0001011299066407926, 'epochs': 550, 'm': 2.7079839415318534}. Best is trial 4 with value: 0.5189751790495908.
[I 2026-10-19 01:49:14,408] A new study created in RDB with name: GAT text-only [v2]

InductGCN                        CV PR-AUC=0.519  {'lr': 0.0004059611610484307, 'weight_decay': 0.0005603803105930283, 'epochs': 450, 'm': 2.8736874205941256}

[I 2026-10-19 01:49:53,317] Trial 0 finished with value: 0.4476358557314786 and parameters: {'lr': 0.0005611516415334506, 'weight_decay': 0.0039847274093219665, 'epochs': 550, 'm': 3.79597545259111}. Best is trial 0 with value: 0.4476358557314786.
[I 2026-10-19 01:50:14,474] Trial 1 finished with value: 0.4741225222555683 and parameters: {'lr': 0.0002051338263087451, 'weight_decay': 0.00010255552094216992, 'epochs': 300, 'm': 4.598528437324806}. Best is trial 1 with value: 0.4741225222555683.
[I 2026-10-19 01:50:35,583] Trial 2 finished with value: 0.44097147334151643 and parameters: {'lr': 0.0015930522616241021, 'weight_decay': 0.0013035123791853842, 'epochs': 300, 'm': 4.909729556485983}. Best is trial 1 with value: 0.4741225222555683.
[I 2026-10-19 01:51:00,319] Trial 3 finished with value: 0.4390285541477186 and parameters: {'lr': 0.004622589001020831, 'weight_decay': 0.0001329377199163636, 'epochs': 350, 'm': 2.5502135295603017}. Best is trial 1 with value: 0.4741225222555683.
[I 2026-10-19 01:51:32,119] Trial 4 finished with value: 0.45108080057140065 and parameters: {'lr': 0.0004059611610484307, 'weight_decay': 0.0005603803105930283, 'epochs': 450, 'm': 2.8736874205941256}. Best is trial 1 with value: 0.4741225222555683.
[I 2026-10-19 01:52:00,789] Trial 5 finished with value: 0.44078463626378717 and parameters: {'lr': 0.0016738085788752138, 'weight_decay': 9.505122659935192e-05, 'epochs': 400, 'm': 3.099085529881075}. Best is trial 1 with value: 0.4741225222555683.
[I 2026-10-19 01:52:25,743] Trial 6 finished with value: 0.4383731414921414 and parameters: {'lr': 0.000816845589476017, 'weight_decay': 0.0018591820902866042, 'epochs': 350, 'm': 3.5427033152408347}. Best is trial 1 with value: 0.4741225222555683.
[I 2026-10-19 01:53:01,494] Trial 7 finished with value: 0.44109061724945725 and parameters: {'lr': 0.0015304852121831463, 'weight_decay': 6.192568649430468e-05, 'epochs': 500, 'm': 2.5115723710618747}. Best is trial 1 with value: 0.4741225222555683.
[I 2026-10-19 01:53:44,198] Trial 8 finished with value: 0.4608837608101319 and parameters: {'lr': 0.00013492834268013249, 'weight_decay': 0.003951309774854116, 'epochs': 600, 'm': 4.425192044349384}. Best is trial 1 with value: 0.4741225222555683.
[I 2026-10-19 01:54:19,717] Trial 9 finished with value: 0.4485747956816605 and parameters: {'lr': 0.0004066563313514797, 'weight_decay': 7.839966958361505e-05, 'epochs': 500, 'm': 3.3204574812188037}. Best is trial 1 with value: 0.4741225222555683.
[I 2026-10-19 01:54:41,212] Trial 10 finished with value: 0.45434863681303117 and parameters: {'lr': 0.00015427099867252974, 'weight_decay': 0.003180368624516101, 'epochs': 300, 'm': 4.567692622415784}. Best is trial 1 with value: 0.4741225222555683.
[I 2026-10-19 01:55:09,538] Trial 11 finished with value: 0.45755311191465353 and parameters: {'lr': 0.00012239319903748565, 'weight_decay': 0.00023025285994798873, 'epochs': 400, 'm': 4.682979938444205}. Best is trial 1 with value: 0.4741225222555683.
[I 2026-10-19 01:55:51,987] Trial 12 finished with value: 0.4370019298693376 and parameters: {'lr': 0.0002802298400780022, 'weight_decay': 0.0008352718854367647, 'epochs': 600, 'm': 4.122375707273699}. Best is trial 1 with value: 0.4741225222555683.
[I 2026-10-19 01:56:20,162] Trial 13 finished with value: 0.43856129763661095 and parameters: {'lr': 0.0004616853924084347, 'weight_decay': 0.000156587764683671, 'epochs': 400, 'm': 4.124243498899308}. Best is trial 1 with value: 0.4741225222555683.
[I 2026-10-19 01:57:02,387] Trial 14 finished with value: 0.459016165721119 and parameters: {'lr': 0.0001493411469598392, 'weight_decay': 0.00012589131779363818, 'epochs': 600, 'm': 4.04402533838707}. Best is trial 1 with value: 0.4741225222555683.
[I 2026-10-19 01:57:37,622] Trial 15 finished with value: 0.44489919858186594 and parameters: {'lr': 0.0003299926992871085, 'weight_decay': 0.0003479800206353882, 'epochs': 500, 'm': 4.973353530447979}. Best is trial 1 with value: 0.4741225222555683.
[I 2026-10-19 01:58:19,954] Trial 16 finished with value: 0.45759557421357827 and parameters: {'lr': 0.00012523019842404374, 'weight_decay': 0.002381786515586863, 'epochs': 600, 'm': 4.874623510671425}. Best is trial 1 with value: 0.4741225222555683.
[I 2026-10-19 01:58:44,892] Trial 17 finished with value: 0.47387228469820253 and parameters: {'lr': 0.00019539986161204011, 'weight_decay': 7.034430600903973e-05, 'epochs': 350, 'm': 4.2534260335043665}. Best is trial 1 with value: 0.4741225222555683.
[I 2026-10-19 01:59:06,348] Trial 18 finished with value: 0.4349154277624091 and parameters: {'lr': 0.00011835478652738646, 'weight_decay': 8.567758600683189e-05, 'epochs': 300, 'm': 3.8633974188339066}. Best is trial 1 with value: 0.4741225222555683.
[I 2026-10-19 01:59:27,722] Trial 19 finished with value: 0.4631593998456859 and parameters: {'lr': 0.0001810339327136358, 'weight_decay': 6.474717735283811e-05, 'epochs': 300, 'm': 4.558564775456215}. Best is trial 1 with value: 0.4741225222555683.
[I 2026-10-19 01:59:49,298] Trial 20 finished with value: 0.46549513329045844 and parameters: {'lr': 0.0002538259827941822, 'weight_decay': 0.00013626150893480702, 'epochs': 300, 'm': 4.101719269895957}. Best is trial 1 with value: 0.4741225222555683.
[I 2026-10-19 02:00:17,822] Trial 21 finished with value: 0.472562896162732 and parameters: {'lr': 0.00016677541107168857, 'weight_decay': 5.513744872802501e-05, 'epochs': 400, 'm': 4.540998188005125}. Best is trial 1 with value: 0.4741225222555683.
[I 2026-10-19 02:00:46,355] Trial 22 finished with value: 0.4586284501895612 and parameters: {'lr': 0.00022028355536905228, 'weight_decay': 9.429861370356454e-05, 'epochs': 400, 'm': 4.9030151997975215}. Best is trial 1 with value: 0.4741225222555683.
[I 2026-10-19 02:01:18,369] Trial 23 finished with value: 0.44206445070865213 and parameters: {'lr': 0.0002604021374074684, 'weight_decay': 6.498274751999233e-05, 'epochs': 450, 'm': 4.3971148817290775}. Best is trial 1 with value: 0.4741225222555683.
[I 2026-10-19 02:01:39,910] Trial 24 finished with value: 0.44064858234828097 and parameters: {'lr': 0.0006837547794775197, 'weight_decay': 0.00013731840280251992, 'epochs': 300, 'm': 4.237682449980264}. Best is trial 1 with value: 0.4741225222555683.
[I 2026-10-19 02:02:04,956] Trial 25 finished with value: 0.43349347858135834 and parameters: {'lr': 0.00045790289268834343, 'weight_decay': 0.00022343548421936463, 'epochs': 350, 'm': 4.6218286400572275}. Best is trial 1 with value: 0.4741225222555683.
[I 2026-10-19 02:02:33,331] Trial 26 finished with value: 0.4494670648147734 and parameters: {'lr': 0.00010467525250205847, 'weight_decay': 5.13908569585068e-05, 'epochs': 400, 'm': 4.669005581977711}. Best is trial 1 with value: 0.4741225222555683.
[I 2026-10-19 02:02:58,273] Trial 27 finished with value: 0.4720207389499733 and parameters: {'lr': 0.0001794662726839833, 'weight_decay': 0.00020458926908697764, 'epochs': 350, 'm': 3.677871512398624}. Best is trial 1 with value: 0.4741225222555683.
[I 2026-10-19 02:03:30,351] Trial 28 finished with value: 0.45719485952412475 and parameters: {'lr': 0.00011125115843540826, 'weight_decay': 5.5859919480012205e-05, 'epochs': 450, 'm': 4.269675919114489}. Best is trial 1 with value: 0.4741225222555683.
[I 2026-10-19 02:03:55,533] Trial 29 finished with value: 0.43847724515306485 and parameters: {'lr': 0.00037174590581762277, 'weight_decay': 6.826026208819597e-05, 'epochs': 350, 'm': 4.667313491408179}. Best is trial 1 with value: 0.4741225222555683.
[I 2026-10-19 02:03:55,600] A new study created in RDB with name: GCN+GAT hybrid [v2]

GAT text-only                    CV PR-AUC=0.474  {'lr': 0.0002051338263087451, 'weight_decay': 0.00010255552094216992, 'epochs': 300, 'm': 4.598528437324806}

[I 2026-10-19 02:04:34,162] Trial 0 finished with value: 0.43288125835275304 and parameters: {'lr': 0.0005611516415334506, 'weight_decay': 0.0039847274093219665, 'epochs': 550, 'm': 3.79597545259111}. Best is trial 0 with value: 0.43288125835275304.
[I 2026-10-19 02:04:55,320] Trial 1 finished with value: 0.4734042730618744 and parameters: {'lr': 0.0002051338263087451, 'weight_decay': 0.00010255552094216992, 'epochs': 300, 'm': 4.598528437324806}. Best is trial 1 with value: 0.4734042730618744.
[I 2026-10-19 02:05:16,362] Trial 2 finished with value: 0.4355669944493321 and parameters: {'lr': 0.0015930522616241021, 'weight_decay': 0.0013035123791853842, 'epochs': 300, 'm': 4.909729556485983}. Best is trial 1 with value: 0.4734042730618744.
[I 2026-10-19 02:05:41,079] Trial 3 finished with value: 0.44567054591909455 and parameters: {'lr': 0.004622589001020831, 'weight_decay': 0.0001329377199163636, 'epochs': 350, 'm': 2.5502135295603017}. Best is trial 1 with value: 0.4734042730618744.
[I 2026-10-19 02:06:12,757] Trial 4 finished with value: 0.4487555519505301 and parameters: {'lr': 0.0004059611610484307, 'weight_decay': 0.0005603803105930283, 'epochs': 450, 'm': 2.8736874205941256}. Best is trial 1 with value: 0.4734042730618744.
[I 2026-10-19 02:06:40,973] Trial 5 finished with value: 0.45536478539740777 and parameters: {'lr': 0.0016738085788752138, 'weight_decay': 9.505122659935192e-05, 'epochs': 400, 'm': 3.099085529881075}. Best is trial 1 with value: 0.4734042730618744.
[I 2026-10-19 02:07:05,769] Trial 6 finished with value: 0.43955750826094553 and parameters: {'lr': 0.000816845589476017, 'weight_decay': 0.0018591820902866042, 'epochs': 350, 'm': 3.5427033152408347}. Best is trial 1 with value: 0.4734042730618744.
[I 2026-10-19 02:07:40,653] Trial 7 finished with value: 0.4372547233431566 and parameters: {'lr': 0.0015304852121831463, 'weight_decay': 6.192568649430468e-05, 'epochs': 500, 'm': 2.5115723710618747}. Best is trial 1 with value: 0.4734042730618744.
[I 2026-10-19 02:08:22,656] Trial 8 finished with value: 0.4910165505778191 and parameters: {'lr': 0.00013492834268013249, 'weight_decay': 0.003951309774854116, 'epochs': 600, 'm': 4.425192044349384}. Best is trial 8 with value: 0.4910165505778191.
[I 2026-10-19 02:08:57,719] Trial 9 finished with value: 0.4405551474178926 and parameters: {'lr': 0.0004066563313514797, 'weight_decay': 7.839966958361505e-05, 'epochs': 500, 'm': 3.3204574812188037}. Best is trial 8 with value: 0.4910165505778191.
[I 2026-10-19 02:09:39,754] Trial 10 finished with value: 0.4289315497355063 and parameters: {'lr': 0.0031729731388564974, 'weight_decay': 0.0029990757980165703, 'epochs': 600, 'm': 4.236140743844462}. Best is trial 8 with value: 0.4910165505778191.
[I 2026-10-19 02:10:07,806] Trial 11 finished with value: 0.46861751961979464 and parameters: {'lr': 0.00011793175904336621, 'weight_decay': 0.0012994291502582335, 'epochs': 400, 'm': 4.52788322703883}. Best is trial 8 with value: 0.4910165505778191.
[I 2026-10-19 02:10:46,705] Trial 12 finished with value: 0.4801236311335819 and parameters: {'lr': 0.00010689886279924621, 'weight_decay': 9.822837538337442e-05, 'epochs': 550, 'm': 4.504016361717566}. Best is trial 8 with value: 0.4910165505778191.
[I 2026-10-19 02:11:28,852] Trial 13 finished with value: 0.4668993220223531 and parameters: {'lr': 0.00017680698828951297, 'weight_decay': 0.0006344540966574601, 'epochs': 600, 'm': 4.701478515675735}. Best is trial 8 with value: 0.4910165505778191.
[I 2026-10-19 02:12:07,571] Trial 14 finished with value: 0.4852930783569608 and parameters: {'lr': 0.00010888655441366942, 'weight_decay': 8.999600719079854e-05, 'epochs': 550, 'm': 4.336823203257932}. Best is trial 8 with value: 0.4910165505778191.
[I 2026-10-19 02:12:46,167] Trial 15 finished with value: 0.48875857189831806 and parameters: {'lr': 0.000130884960706443, 'weight_decay': 0.00048220587776114126, 'epochs': 550, 'm': 3.635113237174212}. Best is trial 8 with value: 0.4910165505778191.
[I 2026-10-19 02:13:28,649] Trial 16 finished with value: 0.44122178929330824 and parameters: {'lr': 0.00028957810482988904, 'weight_decay': 0.0008208749054430918, 'epochs': 600, 'm': 3.6475687859800203}. Best is trial 8 with value: 0.4910165505778191.
[I 2026-10-19 02:14:10,973] Trial 17 finished with value: 0.48627739403094505 and parameters: {'lr': 0.0001440331609215122, 'weight_decay': 0.003523174584791757, 'epochs': 600, 'm': 4.070113057998817}. Best is trial 8 with value: 0.4910165505778191.
[I 2026-10-19 02:14:49,936] Trial 18 finished with value: 0.4463694868121857 and parameters: {'lr': 0.0002784480024252474, 'weight_decay': 0.0012621549152182095, 'epochs': 550, 'm': 4.196997852143135}. Best is trial 8 with value: 0.4910165505778191.
[I 2026-10-19 02:15:32,543] Trial 19 finished with value: 0.42914832233493 and parameters: {'lr': 0.0003415371456515181, 'weight_decay': 0.002339321683755506, 'epochs': 600, 'm': 4.865521205223631}. Best is trial 8 with value: 0.4910165505778191.
[I 2026-10-19 02:16:11,130] Trial 20 finished with value: 0.48683121443889454 and parameters: {'lr': 0.00011181791365405202, 'weight_decay': 0.0011433470260025802, 'epochs': 550, 'm': 3.7236227422298036}. Best is trial 8 with value: 0.4910165505778191.
[I 2026-10-19 02:16:53,270] Trial 21 finished with value: 0.4850201691075 and parameters: {'lr': 0.00012147898303687059, 'weight_decay': 0.00028881892958852626, 'epochs': 600, 'm': 3.4805392530946895}. Best is trial 8 with value: 0.4910165505778191.
[I 2026-10-19 02:17:28,994] Trial 22 finished with value: 0.4869559276122631 and parameters: {'lr': 0.00017282865985750003, 'weight_decay': 0.001056788471656918, 'epochs': 500, 'm': 3.4033975915499717}. Best is trial 8 with value: 0.4910165505778191.
[I 2026-10-19 02:18:07,933] Trial 23 finished with value: 0.4914857032756421 and parameters: {'lr': 0.00015931668331759015, 'weight_decay': 0.0005005575623145282, 'epochs': 550, 'm': 2.8569190382181273}. Best is trial 23 with value: 0.4914857032756421.
[I 2026-10-19 02:18:51,234] Trial 24 finished with value: 0.46230886167857355 and parameters: {'lr': 0.0002102945221618861, 'weight_decay': 0.0009257418617972339, 'epochs': 600, 'm': 2.9094776227032777}. Best is trial 23 with value: 0.4914857032756421.
[I 2026-10-19 02:19:32,718] Trial 25 finished with value: 0.44617947421372367 and parameters: {'lr': 0.0002784440688703396, 'weight_decay': 0.00026623397368190935, 'epochs': 550, 'm': 4.1300888812503205}. Best is trial 23 with value: 0.4914857032756421.
[I 2026-10-19 02:20:11,858] Trial 26 finished with value: 0.49223213893506734 and parameters: {'lr': 0.0001543764029529463, 'weight_decay': 0.0003668214819352929, 'epochs': 550, 'm': 2.5798596978116803}. Best is trial 26 with value: 0.49223213893506734.
[I 2026-10-19 02:20:54,216] Trial 27 finished with value: 0.46542314820491243 and parameters: {'lr': 0.00019238881070703464, 'weight_decay': 0.00028931809578499007, 'epochs': 600, 'm': 3.0624040727018453}. Best is trial 26 with value: 0.49223213893506734.
[I 2026-10-19 02:21:33,128] Trial 28 finished with value: 0.4945119622000055 and parameters: {'lr': 0.0001155251689679663, 'weight_decay': 0.00019384322194510354, 'epochs': 550, 'm': 2.397750211381382}. Best is trial 28 with value: 0.4945119622000055.
[I 2026-10-19 02:22:12,134] Trial 29 finished with value: 0.4944287845740467 and parameters: {'lr': 0.00011512636702980718, 'weight_decay': 0.0003742374071401155, 'epochs': 550, 'm': 2.3305673798546813}. Best is trial 28 with value: 0.4945119622000055.
[I 2026-10-19 02:22:12,204] A new study created in RDB with name: EmpathGCN [v2]

GCN+GAT hybrid                   CV PR-AUC=0.495  {'lr': 0.0001155251689679663, 'weight_decay': 0.00019384322194510354, 'epochs': 550, 'm': 2.397750211381382}

[I 2026-10-19 02:22:47,432] Trial 0 finished with value: 0.5685600917769045 and parameters: {'lr': 0.0005611516415334506, 'weight_decay': 0.0039847274093219665, 'epochs': 550, 'm': 3.79597545259111}. Best is trial 0 with value: 0.5685600917769045.
[I 2026-10-19 02:23:06,605] Trial 1 finished with value: 0.43148366358987 and parameters: {'lr': 0.0002051338263087451, 'weight_decay': 0.00010255552094216992, 'epochs': 300, 'm': 4.598528437324806}. Best is trial 0 with value: 0.5685600917769045.
[I 2026-10-19 02:23:25,880] Trial 2 finished with value: 0.5645098112279887 and parameters: {'lr': 0.0015930522616241021, 'weight_decay': 0.0013035123791853842, 'epochs': 300, 'm': 4.909729556485983}. Best is trial 0 with value: 0.5685600917769045.
[I 2026-10-19 02:23:48,421] Trial 3 finished with value: 0.6073080502265458 and parameters: {'lr': 0.004622589001020831, 'weight_decay': 0.0001329377199163636, 'epochs': 350, 'm': 2.5502135295603017}. Best is trial 3 with value: 0.6073080502265458.
[I 2026-10-19 02:24:17,300] Trial 4 finished with value: 0.5131759223303527 and parameters: {'lr': 0.0004059611610484307, 'weight_decay': 0.0005603803105930283, 'epochs': 450, 'm': 2.8736874205941256}. Best is trial 3 with value: 0.6073080502265458.
[I 2026-10-19 02:24:43,096] Trial 5 finished with value: 0.555270786858761 and parameters: {'lr': 0.0016738085788752138, 'weight_decay': 9.505122659935192e-05, 'epochs': 400, 'm': 3.099085529881075}. Best is trial 3 with value: 0.6073080502265458.
[I 2026-10-19 02:25:05,668] Trial 6 finished with value: 0.5451038831089365 and parameters: {'lr': 0.000816845589476017, 'weight_decay': 0.0018591820902866042, 'epochs': 350, 'm': 3.5427033152408347}. Best is trial 3 with value: 0.6073080502265458.
[I 2026-10-19 02:25:37,494] Trial 7 finished with value: 0.5793442025928758 and parameters: {'lr': 0.0015304852121831463, 'weight_decay': 6.192568649430468e-05, 'epochs': 500, 'm': 2.5115723710618747}. Best is trial 3 with value: 0.6073080502265458.
[I 2026-10-19 02:26:15,697] Trial 8 finished with value: 0.4450460236169836 and parameters: {'lr': 0.00013492834268013249, 'weight_decay': 0.003951309774854116, 'epochs': 600, 'm': 4.425192044349384}. Best is trial 3 with value: 0.6073080502265458.
[I 2026-10-19 02:26:47,568] Trial 9 finished with value: 0.5257138391339262 and parameters: {'lr': 0.0004066563313514797, 'weight_decay': 7.839966958361505e-05, 'epochs': 500, 'm': 3.3204574812188037}. Best is trial 3 with value: 0.6073080502265458.
[I 2026-10-19 02:27:06,968] Trial 10 finished with value: 0.5051037676674894 and parameters: {'lr': 0.00650306212414832, 'weight_decay': 0.0007149336374309071, 'epochs': 300, 'm': 2.1989967618885427}. Best is trial 3 with value: 0.6073080502265458.
[I 2026-10-19 02:27:38,989] Trial 11 finished with value: 0.5931749301191238 and parameters: {'lr': 0.0016212369792701613, 'weight_decay': 5.4078156617388586e-05, 'epochs': 500, 'm': 2.3675695402982337}. Best is trial 3 with value: 0.6073080502265458.
[I 2026-10-19 02:28:14,117] Trial 12 finished with value: 0.6050093241218757 and parameters: {'lr': 0.0021957096641374153, 'weight_decay': 0.0002820775624064714, 'epochs': 550, 'm': 2.833410362520319}. Best is trial 3 with value: 0.6073080502265458.
[I 2026-10-19 02:28:52,491] Trial 13 finished with value: 0.559266916737385 and parameters: {'lr': 0.005554472572268187, 'weight_decay': 0.0005589658702873122, 'epochs': 600, 'm': 2.5806656815875164}. Best is trial 3 with value: 0.6073080502265458.
[I 2026-10-19 02:29:11,698] Trial 14 finished with value: 0.5834202478160232 and parameters: {'lr': 0.00169078165581915, 'weight_decay': 7.997396562692543e-05, 'epochs': 300, 'm': 2.3303152680861547}. Best is trial 3 with value: 0.6073080502265458.
[I 2026-10-19 02:29:37,253] Trial 15 finished with value: 0.5912690083512996 and parameters: {'lr': 0.0031872777461000334, 'weight_decay': 0.0002161824814336733, 'epochs': 400, 'm': 2.8077501089605077}. Best is trial 3 with value: 0.6073080502265458.
[I 2026-10-19 02:30:09,137] Trial 16 finished with value: 0.5713442068108439 and parameters: {'lr': 0.00215431994839431, 'weight_decay': 0.00027073806448773045, 'epochs': 500, 'm': 3.3878811956771284}. Best is trial 3 with value: 0.6073080502265458.
[I 2026-10-19 02:30:28,269] Trial 17 finished with value: 0.6052121131110452 and parameters: {'lr': 0.0013064049091213498, 'weight_decay': 0.0002270842483980269, 'epochs': 300, 'm': 2.432989150839413}. Best is trial 3 with value: 0.6073080502265458.
[I 2026-10-19 02:30:50,675] Trial 18 finished with value: 0.5976093064543413 and parameters: {'lr': 0.001202656096259729, 'weight_decay': 0.00020047871496107746, 'epochs': 350, 'm': 2.180935204653832}. Best is trial 3 with value: 0.6073080502265458.
[I 2026-10-19 02:31:13,176] Trial 19 finished with value: 0.6072205638821093 and parameters: {'lr': 0.004547784729358545, 'weight_decay': 6.155307059483872e-05, 'epochs': 350, 'm': 3.3969850240170265}. Best is trial 3 with value: 0.6073080502265458.
[I 2026-10-19 02:31:32,532] Trial 20 finished with value: 0.5456754494238557 and parameters: {'lr': 0.00507810345908602, 'weight_decay': 6.73340977853924e-05, 'epochs': 300, 'm': 2.624288337183754}. Best is trial 3 with value: 0.6073080502265458.
[I 2026-10-19 02:31:58,412] Trial 21 finished with value: 0.5928525593512479 and parameters: {'lr': 0.0015273462285167066, 'weight_decay': 0.00010373825740288232, 'epochs': 400, 'm': 4.085096073421875}. Best is trial 3 with value: 0.6073080502265458.
[I 2026-10-19 02:32:17,915] Trial 22 finished with value: 0.5113390893712987 and parameters: {'lr': 0.003245040878599745, 'weight_decay': 6.684421628010923e-05, 'epochs': 300, 'm': 3.637512233298696}. Best is trial 3 with value: 0.6073080502265458.
[I 2026-10-19 02:32:43,640] Trial 23 finished with value: 0.6016726003601752 and parameters: {'lr': 0.003436455012038546, 'weight_decay': 6.652236740630411e-05, 'epochs': 400, 'm': 3.4595930953834917}. Best is trial 3 with value: 0.6073080502265458.
[I 2026-10-19 02:33:02,971] Trial 24 finished with value: 0.5486011521099456 and parameters: {'lr': 0.003102134073208651, 'weight_decay': 0.00016106399291556116, 'epochs': 300, 'm': 2.627029211362502}. Best is trial 3 with value: 0.6073080502265458.
[I 2026-10-19 02:33:22,267] Trial 25 finished with value: 0.5062112860265198 and parameters: {'lr': 0.000643865533713662, 'weight_decay': 0.00017456244546492356, 'epochs': 300, 'm': 2.928708765051837}. Best is trial 3 with value: 0.6073080502265458.
[I 2026-10-19 02:33:44,820] Trial 26 finished with value: 0.6210225755275635 and parameters: {'lr': 0.0036313402466388546, 'weight_decay': 0.00011657077151761457, 'epochs': 350, 'm': 2.116585750006478}. Best is trial 26 with value: 0.6210225755275635.
[I 2026-10-19 02:34:07,444] Trial 27 finished with value: 0.6140468134426968 and parameters: {'lr': 0.006583735755182132, 'weight_decay': 6.475689898895849e-05, 'epochs': 350, 'm': 2.1415299046586465}. Best is trial 26 with value: 0.6210225755275635.
[I 2026-10-19 02:34:33,027] Trial 28 finished with value: 0.554820814845342 and parameters: {'lr': 0.007563397302804113, 'weight_decay': 0.00012414767500263982, 'epochs': 400, 'm': 2.840959060941973}. Best is trial 26 with value: 0.6210225755275635.
[I 2026-10-19 02:34:55,408] Trial 29 finished with value: 0.6079396139036012 and parameters: {'lr': 0.0028370533534057035, 'weight_decay': 0.00010162944641746579, 'epochs': 350, 'm': 2.0103363141594026}. Best is trial 26 with value: 0.6210225755275635.
[I 2026-10-19 02:34:55,494] A new study created in RDB with name: GAT-GCN-FeExtr (Empath graph) [v2]

EmpathGCN                        CV PR-AUC=0.621  {'lr': 0.0036313402466388546, 'weight_decay': 0.00011657077151761457, 'epochs': 350, 'm': 2.116585750006478}

[I 2026-10-19 02:35:38,399] Trial 0 finished with value: 0.49350702671109664 and parameters: {'lr': 0.0005611516415334506, 'weight_decay': 0.0039847274093219665, 'epochs': 550, 'm': 3.79597545259111}. Best is trial 0 with value: 0.49350702671109664.
[I 2026-10-19 02:36:01,911] Trial 1 finished with value: 0.47538341873708206 and parameters: {'lr': 0.0002051338263087451, 'weight_decay': 0.00010255552094216992, 'epochs': 300, 'm': 4.598528437324806}. Best is trial 0 with value: 0.49350702671109664.
[I 2026-10-19 02:36:25,254] Trial 2 finished with value: 0.482672594224869 and parameters: {'lr': 0.0015930522616241021, 'weight_decay': 0.0013035123791853842, 'epochs': 300, 'm': 4.909729556485983}. Best is trial 0 with value: 0.49350702671109664.
[I 2026-10-19 02:36:52,634] Trial 3 finished with value: 0.5242167205986143 and parameters: {'lr': 0.004622589001020831, 'weight_decay': 0.0001329377199163636, 'epochs': 350, 'm': 2.5502135295603017}. Best is trial 3 with value: 0.5242167205986143.
[I 2026-10-19 02:37:27,766] Trial 4 finished with value: 0.4953017069747523 and parameters: {'lr': 0.0004059611610484307, 'weight_decay': 0.0005603803105930283, 'epochs': 450, 'm': 2.8736874205941256}. Best is trial 3 with value: 0.5242167205986143.
[I 2026-10-19 02:37:59,239] Trial 5 finished with value: 0.5240926203606286 and parameters: {'lr': 0.0016738085788752138, 'weight_decay': 9.505122659935192e-05, 'epochs': 400, 'm': 3.099085529881075}. Best is trial 3 with value: 0.5242167205986143.
[I 2026-10-19 02:38:26,592] Trial 6 finished with value: 0.4864610171406818 and parameters: {'lr': 0.000816845589476017, 'weight_decay': 0.0018591820902866042, 'epochs': 350, 'm': 3.5427033152408347}. Best is trial 3 with value: 0.5242167205986143.
[I 2026-10-19 02:39:05,843] Trial 7 finished with value: 0.5418950312183045 and parameters: {'lr': 0.0015304852121831463, 'weight_decay': 6.192568649430468e-05, 'epochs': 500, 'm': 2.5115723710618747}. Best is trial 7 with value: 0.5418950312183045.
[I 2026-10-19 02:39:52,718] Trial 8 finished with value: 0.5137083317258726 and parameters: {'lr': 0.00013492834268013249, 'weight_decay': 0.003951309774854116, 'epochs': 600, 'm': 4.425192044349384}. Best is trial 7 with value: 0.5418950312183045.
[I 2026-10-19 02:40:31,851] Trial 9 finished with value: 0.48880431103031396 and parameters: {'lr': 0.0004066563313514797, 'weight_decay': 7.839966958361505e-05, 'epochs': 500, 'm': 3.3204574812188037}. Best is trial 7 with value: 0.5418950312183045.
[I 2026-10-19 02:41:10,725] Trial 10 finished with value: 0.5271376651145203 and parameters: {'lr': 0.00739966347358655, 'weight_decay': 5.66510069556309e-05, 'epochs': 500, 'm': 4.148262592191734}. Best is trial 7 with value: 0.5418950312183045.
[I 2026-10-19 02:41:49,836] Trial 11 finished with value: 0.5214431943289225 and parameters: {'lr': 0.006601104689133519, 'weight_decay': 6.7969166155403e-05, 'epochs': 500, 'm': 3.843198135991293}. Best is trial 7 with value: 0.5418950312183045.
[I 2026-10-19 02:42:28,625] Trial 12 finished with value: 0.5302580688959982 and parameters: {'lr': 0.001464437790264951, 'weight_decay': 0.00015381643019698535, 'epochs': 500, 'm': 3.8281045905122646}. Best is trial 7 with value: 0.5418950312183045.
[I 2026-10-19 02:43:11,531] Trial 13 finished with value: 0.5153300728553277 and parameters: {'lr': 0.0008866924046972871, 'weight_decay': 9.394836722987719e-05, 'epochs': 550, 'm': 4.85275467636669}. Best is trial 7 with value: 0.5418950312183045.
[I 2026-10-19 02:43:46,566] Trial 14 finished with value: 0.4995423031119024 and parameters: {'lr': 0.0015200930172674337, 'weight_decay': 6.883521794485005e-05, 'epochs': 450, 'm': 4.092176244382888}. Best is trial 7 with value: 0.5418950312183045.
[I 2026-10-19 02:44:25,564] Trial 15 finished with value: 0.5453069357745066 and parameters: {'lr': 0.00333191982759438, 'weight_decay': 8.09183280330631e-05, 'epochs': 500, 'm': 2.173557231831598}. Best is trial 15 with value: 0.5453069357745066.
[I 2026-10-19 02:45:04,252] Trial 16 finished with value: 0.5495731793845627 and parameters: {'lr': 0.0041596307192950654, 'weight_decay': 0.00023847191524144332, 'epochs': 500, 'm': 2.481549002812393}. Best is trial 16 with value: 0.5495731793845627.
[I 2026-10-19 02:45:46,963] Trial 17 finished with value: 0.5482820269793532 and parameters: {'lr': 0.0058848039724618065, 'weight_decay': 8.555938209740389e-05, 'epochs': 550, 'm': 2.3300675085383307}. Best is trial 16 with value: 0.5495731793845627.
[I 2026-10-19 02:46:30,282] Trial 18 finished with value: 0.5116415763645996 and parameters: {'lr': 0.008106819067606841, 'weight_decay': 0.00021674700768549142, 'epochs': 550, 'm': 2.4692825288720504}. Best is trial 16 with value: 0.5495731793845627.
[I 2026-10-19 02:47:17,253] Trial 19 finished with value: 0.55622333884569 and parameters: {'lr': 0.0016300433602266092, 'weight_decay': 0.00017900928033495452, 'epochs': 600, 'm': 2.0108553240716645}. Best is trial 19 with value: 0.55622333884569.
[I 2026-10-19 02:48:04,028] Trial 20 finished with value: 0.5561853061951817 and parameters: {'lr': 0.0016400453699673368, 'weight_decay': 0.00017591607511354925, 'epochs': 600, 'm': 2.4848069327451068}. Best is trial 19 with value: 0.55622333884569.
[I 2026-10-19 02:48:50,618] Trial 21 finished with value: 0.5467297020172397 and parameters: {'lr': 0.0014917267489104342, 'weight_decay': 0.000344357965883129, 'epochs': 600, 'm': 2.857929950676651}. Best is trial 19 with value: 0.55622333884569.
[I 2026-10-19 02:49:33,353] Trial 22 finished with value: 0.54564223496957 and parameters: {'lr': 0.0011858608424451767, 'weight_decay': 0.0002079011779737297, 'epochs': 550, 'm': 2.0057698155664414}. Best is trial 19 with value: 0.55622333884569.
[I 2026-10-19 02:50:19,810] Trial 23 finished with value: 0.5474580752156626 and parameters: {'lr': 0.004716495746148538, 'weight_decay': 0.0002493575365159401, 'epochs': 600, 'm': 3.4266913574247906}. Best is trial 19 with value: 0.55622333884569.
[I 2026-10-19 02:51:06,387] Trial 24 finished with value: 0.5577355816528078 and parameters: {'lr': 0.0030407178709186385, 'weight_decay': 8.810302346794737e-05, 'epochs': 600, 'm': 2.677641849102402}. Best is trial 24 with value: 0.5577355816528078.
[I 2026-10-19 02:51:52,835] Trial 25 finished with value: 0.49659638896272973 and parameters: {'lr': 0.0006605259295330892, 'weight_decay': 0.00032353866389965444, 'epochs': 600, 'm': 2.5252958579841294}. Best is trial 24 with value: 0.5577355816528078.
[I 2026-10-19 02:52:40,056] Trial 26 finished with value: 0.5430491225335188 and parameters: {'lr': 0.002742954307188161, 'weight_decay': 8.751656832394263e-05, 'epochs': 600, 'm': 2.203529219919882}. Best is trial 24 with value: 0.5577355816528078.
[I 2026-10-19 02:53:23,265] Trial 27 finished with value: 0.548465146540611 and parameters: {'lr': 0.002850555704515108, 'weight_decay': 0.00013026615813812952, 'epochs': 550, 'm': 2.9333820029493043}. Best is trial 24 with value: 0.5577355816528078.
[I 2026-10-19 02:54:06,418] Trial 28 finished with value: 0.4889503779938111 and parameters: {'lr': 0.00048822851521854096, 'weight_decay': 7.666764300186164e-05, 'epochs': 550, 'm': 2.048573425653734}. Best is trial 24 with value: 0.5577355816528078.
[I 2026-10-19 02:54:53,542] Trial 29 finished with value: 0.49325176054720016 and parameters: {'lr': 0.0003869446168436365, 'weight_decay': 0.0004087673636993801, 'epochs': 600, 'm': 2.0922163608860527}. Best is trial 24 with value: 0.5577355816528078.
[I 2026-10-19 02:54:53,615] A new study created in RDB with name: GAT-GCN-FeExtr (word graph) [v2]

GAT-GCN-FeExtr (Empath graph)    CV PR-AUC=0.558  {'lr': 0.0030407178709186385, 'weight_decay': 8.810302346794737e-05, 'epochs': 600, 'm': 2.677641849102402}

[I 2026-10-19 02:55:37,220] Trial 0 finished with value: 0.4400357491536462 and parameters: {'lr': 0.0005611516415334506, 'weight_decay': 0.0039847274093219665, 'epochs': 550, 'm': 3.79597545259111}. Best is trial 0 with value: 0.4400357491536462.
[I 2026-10-19 02:56:01,012] Trial 1 finished with value: 0.4861386017361091 and parameters: {'lr': 0.0002051338263087451, 'weight_decay': 0.00010255552094216992, 'epochs': 300, 'm': 4.598528437324806}. Best is trial 1 with value: 0.4861386017361091.
[I 2026-10-19 02:56:24,922] Trial 2 finished with value: 0.4423130268072424 and parameters: {'lr': 0.0015930522616241021, 'weight_decay': 0.0013035123791853842, 'epochs': 300, 'm': 4.909729556485983}. Best is trial 1 with value: 0.4861386017361091.
[I 2026-10-19 02:56:52,513] Trial 3 finished with value: 0.46392612410228573 and parameters: {'lr': 0.004622589001020831, 'weight_decay': 0.0001329377199163636, 'epochs': 350, 'm': 2.5502135295603017}. Best is trial 1 with value: 0.4861386017361091.
[I 2026-10-19 02:57:27,876] Trial 4 finished with value: 0.45312138567386506 and parameters: {'lr': 0.0004059611610484307, 'weight_decay': 0.0005603803105930283, 'epochs': 450, 'm': 2.8736874205941256}. Best is trial 1 with value: 0.4861386017361091.
[I 2026-10-19 02:57:59,547] Trial 5 finished with value: 0.4594539594308152 and parameters: {'lr': 0.0016738085788752138, 'weight_decay': 9.505122659935192e-05, 'epochs': 400, 'm': 3.099085529881075}. Best is trial 1 with value: 0.4861386017361091.
[I 2026-10-19 02:58:27,254] Trial 6 finished with value: 0.4427729844575409 and parameters: {'lr': 0.000816845589476017, 'weight_decay': 0.0018591820902866042, 'epochs': 350, 'm': 3.5427033152408347}. Best is trial 1 with value: 0.4861386017361091.
[I 2026-10-19 02:59:06,571] Trial 7 finished with value: 0.44529079090849966 and parameters: {'lr': 0.0015304852121831463, 'weight_decay': 6.192568649430468e-05, 'epochs': 500, 'm': 2.5115723710618747}. Best is trial 1 with value: 0.4861386017361091.
[I 2026-10-19 02:59:53,621] Trial 8 finished with value: 0.4769581699987943 and parameters: {'lr': 0.00013492834268013249, 'weight_decay': 0.003951309774854116, 'epochs': 600, 'm': 4.425192044349384}. Best is trial 1 with value: 0.4861386017361091.
[I 2026-10-19 03:00:32,727] Trial 9 finished with value: 0.44482219632653197 and parameters: {'lr': 0.0004066563313514797, 'weight_decay': 7.839966958361505e-05, 'epochs': 500, 'm': 3.3204574812188037}. Best is trial 1 with value: 0.4861386017361091.
[I 2026-10-19 03:00:56,560] Trial 10 finished with value: 0.48262612172294717 and parameters: {'lr': 0.00015427099867252974, 'weight_decay': 0.003180368624516101, 'epochs': 300, 'm': 4.567692622415784}. Best is trial 1 with value: 0.4861386017361091.
[I 2026-10-19 03:01:20,392] Trial 11 finished with value: 0.4745755690314963 and parameters: {'lr': 0.00011993397929704987, 'weight_decay': 0.0012940915571701124, 'epochs': 300, 'm': 4.588963942840556}. Best is trial 1 with value: 0.4861386017361091.
[I 2026-10-19 03:01:48,032] Trial 12 finished with value: 0.4738886440136385 and parameters: {'lr': 0.0002704548313232621, 'weight_decay': 8.309649026737602e-05, 'epochs': 350, 'm': 4.07526155515481}. Best is trial 1 with value: 0.4861386017361091.
[I 2026-10-19 03:02:19,348] Trial 13 finished with value: 0.4825947081581762 and parameters: {'lr': 0.0002095093508986763, 'weight_decay': 0.0002188444484144763, 'epochs': 400, 'm': 4.979752310794549}. Best is trial 1 with value: 0.4861386017361091.
[I 2026-10-19 03:02:43,087] Trial 14 finished with value: 0.45579276647484157 and parameters: {'lr': 0.00038663390479792164, 'weight_decay': 0.0012710092256841504, 'epochs': 300, 'm': 4.2047220064678354}. Best is trial 1 with value: 0.4861386017361091.
[I 2026-10-19 03:03:06,760] Trial 15 finished with value: 0.4751961172264542 and parameters: {'lr': 0.00014360777883540467, 'weight_decay': 0.0002539561586165552, 'epochs': 300, 'm': 3.760272112046609}. Best is trial 1 with value: 0.4861386017361091.
[I 2026-10-19 03:03:42,062] Trial 16 finished with value: 0.4547235685110713 and parameters: {'lr': 0.0003149111553663107, 'weight_decay': 0.0012287977120416201, 'epochs': 450, 'm': 4.323934957981344}. Best is trial 1 with value: 0.4861386017361091.
[I 2026-10-19 03:04:09,488] Trial 17 finished with value: 0.48231484073221975 and parameters: {'lr': 0.00015901044703106658, 'weight_decay': 0.0036117824616163753, 'epochs': 350, 'm': 4.16154439023259}. Best is trial 1 with value: 0.4861386017361091.
[I 2026-10-19 03:04:33,081] Trial 18 finished with value: 0.4410629197170808 and parameters: {'lr': 0.0012209227884309184, 'weight_decay': 6.838226388401934e-05, 'epochs': 300, 'm': 4.805928579133065}. Best is trial 1 with value: 0.4861386017361091.
[I 2026-10-19 03:05:04,413] Trial 19 finished with value: 0.44980928017424343 and parameters: {'lr': 0.0003738576522482506, 'weight_decay': 0.0030726074082764107, 'epochs': 400, 'm': 4.970367443537019}. Best is trial 1 with value: 0.4861386017361091.
[I 2026-10-19 03:05:36,047] Trial 20 finished with value: 0.48868288276489386 and parameters: {'lr': 0.00018462686313034564, 'weight_decay': 0.00019001928892591454, 'epochs': 400, 'm': 4.0442322168047795}. Best is trial 20 with value: 0.48868288276489386.
[I 2026-10-19 03:06:07,882] Trial 21 finished with value: 0.4886422793715508 and parameters: {'lr': 0.00016677541107168857, 'weight_decay': 5.513744872802501e-05, 'epochs': 400, 'm': 4.540998188005125}. Best is trial 20 with value: 0.48868288276489386.
[I 2026-10-19 03:06:35,536] Trial 22 finished with value: 0.4912585347964057 and parameters: {'lr': 0.0001974679003863818, 'weight_decay': 0.00022601745015481687, 'epochs': 350, 'm': 4.4189410240621845}. Best is trial 22 with value: 0.4912585347964057.
[I 2026-10-19 03:07:11,245] Trial 23 finished with value: 0.4890787623579362 and parameters: {'lr': 0.00017458970489168298, 'weight_decay': 0.00012340195764405822, 'epochs': 450, 'm': 3.831695161555727}. Best is trial 22 with value: 0.4912585347964057.
[I 2026-10-19 03:07:50,418] Trial 24 finished with value: 0.4597040660034855 and parameters: {'lr': 0.00022034614485974782, 'weight_decay': 0.00020821330812578997, 'epochs': 500, 'm': 3.7461190474228756}. Best is trial 22 with value: 0.4912585347964057.
[I 2026-10-19 03:08:21,820] Trial 25 finished with value: 0.48434973555691807 and parameters: {'lr': 0.00014087321228628094, 'weight_decay': 0.000404044647814016, 'epochs': 400, 'm': 4.162752204980419}. Best is trial 22 with value: 0.4912585347964057.
[I 2026-10-19 03:08:57,057] Trial 26 finished with value: 0.4825245732452019 and parameters: {'lr': 0.00010492168295159611, 'weight_decay': 5.3405325970746416e-05, 'epochs': 450, 'm': 4.203572509637145}. Best is trial 22 with value: 0.4912585347964057.
[I 2026-10-19 03:09:28,542] Trial 27 finished with value: 0.48449766147988615 and parameters: {'lr': 0.00015105974252803647, 'weight_decay': 0.00043481738056419674, 'epochs': 400, 'm': 4.808858212583186}. Best is trial 22 with value: 0.4912585347964057.
[I 2026-10-19 03:09:56,048] Trial 28 finished with value: 0.44508582281475945 and parameters: {'lr': 0.0004117843683966706, 'weight_decay': 0.0002784677054968702, 'epochs': 350, 'm': 4.6171099269119305}. Best is trial 22 with value: 0.4912585347964057.
[I 2026-10-19 03:10:27,552] Trial 29 finished with value: 0.47839946811791395 and parameters: {'lr': 0.00011776347244363612, 'weight_decay': 0.0001579643719382297, 'epochs': 400, 'm': 3.3284913092194897}. Best is trial 22 with value: 0.4912585347964057.

GAT-GCN-FeExtr (word graph)      CV PR-AUC=0.491  {'lr': 0.0001974679003863818, 'weight_decay': 0.00022601745015481687, 'epochs': 350, 'm': 4.4189410240621845}

1603

## Cross-fitted ensembles, scored once on each held-out cohort

In [ ]:
import numpy as np, pandas as pd
from src.paper1_graph_model.experiment import run_final

def row(model, cohort, m):
    lo, hi = m['f1_macro_ci']
    return {'model': model, 'cohort': cohort, 'n': m['n'], 'positives': m['positives'],
            'tau': round(m['threshold'], 2), 'F1 macro': round(m['f1_macro'], 4),
            'F1 95% CI': f'[{lo:.3f}, {hi:.3f}]', 'recall': round(m['recall'], 3),
            'precision': round(m['precision'], 3), 'specificity': round(m['specificity'], 3),
            'ROC-AUC': round(m.get('roc_auc', np.nan), 3), 'PR-AUC': round(m.get('pr_auc', np.nan), 3),
            'FN': m['fn'], 'FP': m['fp']}

def rows_of(name, res):
    out = [row(name, 'pool (out-of-fold)', res['oof_metrics'])]
    return out + [row(name, c, m) for c, m in res['metrics'].items()]

results, rows = {}, []
for spec in SPECS:
    hp = hp_from_params(spec, best[spec.name]['params'])
    res = run_final(spec, hp, pool, held_out, N_FOLDS, SEEDS_PER_FOLD, SEED, MAX_FPR, DEVICE)
    results[spec.name] = res
    rows += rows_of(spec.name, res)
    print(spec.name, 'tau =', res['tau'], res['tau_info'])
metrics = pd.DataFrame(rows)
metrics.to_csv(RESULTS / 'metrics.csv', index=False)
metrics

InductGCN tau = 0.6 {'fn': 18, 'fp': 30, 'feasible': False, 'max_fpr': 0.2857142857142857}
GAT text-only tau = 0.6 {'fn': 18, 'fp': 30, 'feasible': False, 'max_fpr': 0.2857142857142857}
GCN+GAT hybrid tau = 0.6 {'fn': 18, 'fp': 28, 'feasible': True, 'max_fpr': 0.2857142857142857}
EmpathGCN tau = 0.47 {'fn': 18, 'fp': 24, 'feasible': True, 'max_fpr': 0.2857142857142857}
GAT-GCN-FeExtr (Empath graph) tau = 0.46 {'fn': 19, 'fp': 27, 'feasible': True, 'max_fpr': 0.2857142857142857}
GAT-GCN-FeExtr (word graph) tau = 0.6 {'fn': 18, 'fp': 29, 'feasible': False, 'max_fpr': 0.2857142857142857}

,model,cohort,n,positives,tau,F1 macro,F1 95% CI,recall,precision,specificity,ROC-AUC,PR-AUC,FN,FP
0,InductGCN,pool (out-of-fold),140,42,0.60,0.6196,"[0.533, 0.698]",0.571,0.444,0.694,0.676,0.532,18,30
1,InductGCN,daic_test,46,14,0.60,0.6734,"[0.518, 0.802]",0.714,0.500,0.688,0.650,0.482,4,10
2,InductGCN,edaic,112,34,0.60,0.7130,"[0.618, 0.797]",0.706,0.558,0.756,0.758,0.652,10,19
3,GAT text-only,pool (out-of-fold),140,42,0.60,0.6196,"[0.536, 0.695]",0.571,0.444,0.694,0.681,0.538,18,30
4,GAT text-only,daic_test,46,14,0.60,0.5984,"[0.450, 0.732]",0.571,0.421,0.656,0.636,0.460,6,11
5,GAT text-only,edaic,112,34,0.60,0.6814,"[0.591, 0.764]",0.647,0.524,0.744,0.743,0.646,12,20
6,GCN+GAT hybrid,pool (out-of-fold),140,42,0.60,0.6317,"[0.547, 0.708]",0.571,0.462,0.714,0.679,0.546,18,28
7,GCN+GAT hybrid,daic_test,46,14,0.60,0.6541,"[0.505, 0.781]",0.714,0.476,0.656,0.663,0.479,4,11
8,GCN+GAT hybrid,edaic,112,34,0.60,0.6853,"[0.591, 0.771]",0.676,0.523,0.731,0.773,0.643,11,21
9,EmpathGCN,pool (out-of-fold),140,42,0.47,0.6561,"[0.568, 0.735]",0.571,0.500,0.755,0.680,0.539,18,24
10,EmpathGCN,daic_test,46,14,0.47,0.5965,"[0.440, 0.732]",0.714,0.417,0.562,0.688,0.455,4,14
11,EmpathGCN,edaic,112,34,0.47,0.7083,"[0.608, 0.792]",0.735,0.543,0.731,0.780,0.580,9,21
12,GAT-GCN-FeExtr (Empath graph),pool (out-of-fold),140,42,0.46,0.6277,"[0.541, 0.717]",0.548,0.460,0.724,0.689,0.548,19,27
13,GAT-GCN-FeExtr (Empath graph),daic_test,46,14,0.46,0.7262,"[0.589, 0.846]",0.857,0.545,0.688,0.792,0.536,2,10
14,GAT-GCN-FeExtr (Empath graph),edaic,112,34,0.46,0.6937,"[0.595, 0.786]",0.529,0.600,0.846,0.810,0.613,16,12
15,GAT-GCN-FeExtr (word graph),pool (out-of-fold),140,42,0.60,0.6256,"[0.541, 0.701]",0.571,0.453,0.704,0.665,0.526,18,29
16,GAT-GCN-FeExtr (word graph),daic_test,46,14,0.60,0.6734,"[0.517, 0.797]",0.714,0.500,0.688,0.670,0.496,4,10
17,GAT-GCN-FeExtr (word graph),edaic,112,34,0.60,0.6969,"[0.604, 0.778]",0.706,0.533,0.731,0.764,0.608,10,21

In [ ]:
# Per-participant probabilities stay outside the repository.
for name, res in results.items():
    for c in held_out:
        out = pd.DataFrame({'Participant_ID': c.ids, 'label': c.y, 'prob': res['probs'][c.name]})
        out.to_csv(f"{OUTPUT_DIR}/probs_{name.replace(' ', '_')}_{c.name}.csv", index=False)

## Ablation of the professional-feature views (main model, hyperparameters fixed)

In [ ]:
from dataclasses import replace
MAIN = 'GAT-GCN-FeExtr (Empath graph)'   # change after looking at the table above if needed
main = next(s for s in SPECS if s.name == MAIN)
hp_main = hp_from_params(main, best[main.name]['params'])
ablation = []
for drop in ALL + (None,):
    views = tuple(v for v in ALL if v != drop)
    spec = replace(main, name=f'without {drop}' if drop else 'all views', views=views)
    ablation += rows_of(spec.name, run_final(spec, hp_main, pool, held_out, N_FOLDS, SEEDS_PER_FOLD, SEED, MAX_FPR, DEVICE))
ablation = pd.DataFrame(ablation)
ablation.to_csv(RESULTS / 'ablation_views.csv', index=False)
ablation

,model,cohort,n,positives,tau,F1 macro,F1 95% CI,recall,precision,specificity,ROC-AUC,PR-AUC,FN,FP
0,without temporal,pool (out-of-fold),140,42,0.50,0.6011,"[0.514, 0.683]",0.500,0.429,0.714,0.664,0.512,21,28
1,without temporal,daic_test,46,14,0.50,0.6862,"[0.544, 0.808]",0.857,0.500,0.625,0.688,0.397,2,12
2,without temporal,edaic,112,34,0.50,0.7169,"[0.628, 0.800]",0.824,0.538,0.692,0.807,0.554,6,24
3,without paralinguistic,pool (out-of-fold),140,42,0.50,0.6663,"[0.583, 0.748]",0.595,0.510,0.755,0.679,0.526,17,24
4,without paralinguistic,daic_test,46,14,0.50,0.7310,"[0.596, 0.848]",0.929,0.542,0.656,0.781,0.512,1,11
5,without paralinguistic,edaic,112,34,0.50,0.7125,"[0.613, 0.799]",0.588,0.606,0.833,0.807,0.614,14,13
6,without psycholinguistic,pool (out-of-fold),140,42,0.47,0.5906,"[0.502, 0.672]",0.476,0.417,0.714,0.634,0.552,22,28
7,without psycholinguistic,daic_test,46,14,0.47,0.7718,"[0.630, 0.882]",0.929,0.591,0.719,0.839,0.610,1,9
8,without psycholinguistic,edaic,112,34,0.47,0.6883,"[0.594, 0.783]",0.588,0.556,0.795,0.798,0.627,14,16
9,all views,pool (out-of-fold),140,42,0.43,0.6216,"[0.531, 0.707]",0.548,0.451,0.714,0.688,0.547,19,28
10,all views,daic_test,46,14,0.43,0.7262,"[0.589, 0.846]",0.857,0.545,0.688,0.790,0.526,2,10
11,all views,edaic,112,34,0.43,0.7044,"[0.611, 0.792]",0.588,0.588,0.821,0.813,0.618,14,14

## DSM-5 mapping vs. legacy Empath domain groups (EmpathGCN and main model)

Rebuilds the features with the legacy `EMPATH_DOMAIN_GROUPS` and repeats the final runs with the same hyperparameters.

In [ ]:
cohorts_dom = build_cohorts(data.data_root(), scorer, psycholinguistic='domains')
pool_dom = merge_cohorts('daic_pool', cohorts_dom['daic_train'], cohorts_dom['daic_dev'])
held_dom = [cohorts_dom['daic_test'], cohorts_dom['edaic']]
cmp_rows = []
for name in ['EmpathGCN', MAIN]:
    spec = next(s for s in SPECS if s.name == name)
    hp = hp_from_params(spec, best[name]['params'])
    res_dom = run_final(spec, hp, pool_dom, held_dom, N_FOLDS, SEEDS_PER_FOLD, SEED, MAX_FPR, DEVICE)
    cmp_rows += rows_of(f'{name} / DSM-5 mapping', results[name]) + rows_of(f'{name} / legacy domains', res_dom)
mapping_vs_domains = pd.DataFrame(cmp_rows)
mapping_vs_domains.to_csv(RESULTS / 'mapping_vs_domains.csv', index=False)
mapping_vs_domains

,model,cohort,n,positives,tau,F1 macro,F1 95% CI,recall,precision,specificity,ROC-AUC,PR-AUC,FN,FP
0,EmpathGCN / DSM-5 mapping,pool (out-of-fold),140,42,0.47,0.6561,"[0.568, 0.735]",0.571,0.500,0.755,0.680,0.539,18,24
1,EmpathGCN / DSM-5 mapping,daic_test,46,14,0.47,0.5965,"[0.440, 0.732]",0.714,0.417,0.562,0.688,0.455,4,14
2,EmpathGCN / DSM-5 mapping,edaic,112,34,0.47,0.7083,"[0.608, 0.792]",0.735,0.543,0.731,0.780,0.580,9,21
3,EmpathGCN / legacy domains,pool (out-of-fold),140,42,0.45,0.6415,"[0.552, 0.725]",0.595,0.472,0.714,0.679,0.533,17,28
4,EmpathGCN / legacy domains,daic_test,46,14,0.45,0.5965,"[0.440, 0.732]",0.714,0.417,0.562,0.683,0.456,4,14
5,EmpathGCN / legacy domains,edaic,112,34,0.45,0.6762,"[0.581, 0.761]",0.735,0.500,0.679,0.768,0.566,9,25
6,GAT-GCN-FeExtr (Empath graph) / DSM-5 mapping,pool (out-of-fold),140,42,0.46,0.6277,"[0.541, 0.717]",0.548,0.460,0.724,0.689,0.548,19,27
7,GAT-GCN-FeExtr (Empath graph) / DSM-5 mapping,daic_test,46,14,0.46,0.7262,"[0.589, 0.846]",0.857,0.545,0.688,0.792,0.536,2,10
8,GAT-GCN-FeExtr (Empath graph) / DSM-5 mapping,edaic,112,34,0.46,0.6937,"[0.595, 0.786]",0.529,0.600,0.846,0.810,0.613,16,12
9,GAT-GCN-FeExtr (Empath graph) / legacy domains,pool (out-of-fold),140,42,0.47,0.6415,"[0.552, 0.720]",0.595,0.472,0.714,0.674,0.540,17,28
10,GAT-GCN-FeExtr (Empath graph) / legacy domains,daic_test,46,14,0.47,0.7310,"[0.589, 0.847]",0.929,0.542,0.656,0.830,0.584,1,11
11,GAT-GCN-FeExtr (Empath graph) / legacy domains,edaic,112,34,0.47,0.5557,"[0.454, 0.662]",0.206,0.538,0.923,0.751,0.573,27,6

## Attention over Empath categories (auditability)

Mean attention from each category node to each test participant, averaged over heads and the 20 members.
Per-participant matrices go to `OUTPUT_DIR`; only the class-level ranking is written to the repository.

In [ ]:
from src.paper1_graph_model.experiment import attention_to_vocabulary
test_c = cohorts['daic_test']
att = attention_to_vocabulary(results[main.name], main, test_c, DEVICE)
att.to_csv(f"{OUTPUT_DIR}/attention_test_{main.name.replace(' ', '_')}.csv")
by_class = pd.DataFrame({'control': att[test_c.y == 0].mean(), 'depressed': att[test_c.y == 1].mean()})
by_class['delta'] = by_class['depressed'] - by_class['control']
by_class = by_class.sort_values('delta', ascending=False)
by_class.to_csv(RESULTS / 'attention_by_class_test.csv')
by_class.head(20)

               control  depressed     delta
neglect       0.005902   0.011320  0.005418
health        0.007744   0.011644  0.003899
morning       0.006901   0.010389  0.003487
furniture     0.002458   0.005941  0.003482
aggression    0.007255   0.010267  0.003011
play          0.016272   0.019196  0.002924
gain          0.004198   0.007055  0.002857
timidity      0.009263   0.012087  0.002824
real_estate   0.007126   0.009704  0.002578
occupation    0.009473   0.012028  0.002555
masculine     0.006069   0.008605  0.002536
royalty       0.003192   0.005610  0.002418
ancient       0.005843   0.008171  0.002328
independence  0.004454   0.006732  0.002278
restaurant    0.006254   0.008281  0.002026
competing     0.006381   0.007894  0.001513
technology    0.005641   0.007121  0.001480
car           0.007279   0.008686  0.001407
messaging     0.006168   0.007521  0.001353
cheerfulness  0.006565   0.007886  0.001321